version: "3.8"

services:
  tasmogo:
    image: merlinschumacher/tasmogo
    environment:
      - TASMOGO_DOUPDATES=true
      - TASMOGO_DAEMON=true
      - TASMOGO_CIDR=192.168.178.0/24
      - TZ=Europe/Berlin
    network_mode: host
    restart: always
